
package com.project.web_service.wrappers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.1.4
 * Mon Apr 06 08:27:57 CEST 2009
 * Generated source version: 2.1.4
 */

@XmlRootElement(name = "sayHello", namespace = "http://com.project/web_service/wrappers")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sayHello", namespace = "http://com.project/web_service/wrappers", propOrder = {"firstName","lastName"})

public class SayHello {

    @XmlElement(name = "firstName")
    private java.lang.String firstName;
    @XmlElement(name = "lastName")
    private java.lang.String lastName;

    public java.lang.String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(java.lang.String newFirstName)  {
        this.firstName = newFirstName;
    }

    public java.lang.String getLastName() {
        return this.lastName;
    }

    public void setLastName(java.lang.String newLastName)  {
        this.lastName = newLastName;
    }

}

